"""
generate-ide-config.py — generates .cursorrules, CLAUDE.md, and Antigravity
skill files from templates/agent-rules.yaml, the single source of truth
(SPECS.md §4, §13, §22 Phase 5).

Called by the post-checkout hook instead of embedding IDE-rule content
inline — editing templates/agent-rules.yaml is now the only way to change
what gets written to .cursorrules / CLAUDE.md / .agents/skills/*/skill.md.

Idempotent: never overwrites an existing .cursorrules, CLAUDE.md, or
skill.md (same behavior as the hook's previous `[ ! -f ... ]` guards).

Usage:
    python3 generate-ide-config.py \\
        --repo-root /path/to/repo \\
        --rules-file /path/to/templates/agent-rules.yaml \\
        --stack ts-react|python-fastapi|go|generic \\
        --project-name myproject --owner-id me@example.com \\
        --otel-endpoint http://localhost:6006 --test-cmd "pytest" \\
        --framework-version 1.0.0
"""

from __future__ import annotations

import argparse
import difflib
import os
import subprocess
import sys
from pathlib import Path


def _load_rules(rules_file: Path) -> dict:
    try:
        import yaml  # type: ignore
    except ImportError:
        print(
            "❌ generate-ide-config.py requires pyyaml (pip install -r requirements.txt). "
            "IDE config was NOT regenerated.",
            file=sys.stderr,
        )
        sys.exit(1)
    with rules_file.open() as fh:
        return yaml.safe_load(fh) or {}


def _render_cursorrules(rules: dict, stack: str, ctx: dict[str, str]) -> str:
    lines = [
        "# AgentSmith — Agent Guardrails",
        f"# Project: {ctx['project_name']} | Owner: {ctx['owner_id']}",
        f"# Auto-generated by AgentSmith v{ctx['framework_version']} "
        f"from templates/agent-rules.yaml — do not edit this file directly.",
        "",
    ]

    pillar_titles = {
        1: "REQUIREMENTS & DESIGN",
        2: "BUILD ARCHITECTURE (Ponytail Rules)",
        3: "TRACING & EVALUATIONS",
        4: "TESTING GUARDRAILS",
        5: "OPERATIONS & SELF-IMPROVEMENT",
        6: "INTERFACE CONSTRAINTS (Caveman Compression)",
        7: "STACK-SPECIFIC RULES",
        8: "OBSERVABILITY WIRE",
        9: "MULTI-AGENT ORCHESTRATION",
        10: "COST-OPTIMISATION ROUTING",
    }

    for pillar in rules.get("pillars", []):
        pid = pillar["id"]
        title = pillar_titles.get(pid, pillar["name"].upper())
        rule_text = pillar["rule"].strip()
        # Substitute the same placeholders the old inline heredocs used.
        rule_text = (
            rule_text.replace("$AGENT_PHOENIX_ENDPOINT", ctx["otel_endpoint"])
            .replace("{{OWNER_ID}}", ctx["owner_id"])
            .replace("{{PROJECT_NAME}}", ctx["project_name"])
        )
        lines.append(f"## {pid}. {title}")
        lines.append(f"- {rule_text}")
        if pid == 3:
            lines.append(
                f"- OTel endpoint for this project: {ctx['otel_endpoint']}/v1/traces"
            )
        if pid == 4:
            lines.append(f"- Test command for this project: {ctx['test_cmd']}")
        lines.append("")

    stack_def = (rules.get("stacks") or {}).get(stack)
    if stack_def:
        lines.append(f"## 11. {stack.upper()} ADDENDUM")
        for r in stack_def.get("additional_rules", []):
            lines.append(f"- {r}")
        lines.append("")

    return "\n".join(lines)


def _render_claude_md(ctx: dict[str, str]) -> str:
    return f"""# AgentSmith — Claude Code Instructions
# Project: {ctx["project_name"]} | Owner: {ctx["owner_id"]}
# Auto-generated from templates/agent-rules.yaml — do not edit this file directly.

## Compliance
Follow all rules in `.cursorrules` exactly. They are not suggestions.

## Session Start Checklist
1. Read `.agent-history.log` — surface any unresolved MAJOR/CRITICAL entries to the user.
2. Check `.agent-rfc/` — confirm a spec exists before touching any source file.
3. Query the Knowledge Graph: `python3 scripts/local_knowledge_graph.py` to identify dependencies.

## Test Command
```
{ctx["test_cmd"]}
```

## Observability
- OTel endpoint: {ctx["otel_endpoint"]}/v1/traces
- Emit spans for every tool call, LLM invocation, and file write.

## Output Format
Code only. No preambles. No summaries. No explanations outside inline comments.
"""


def _render_skill(skill: dict, rules: dict, ctx: dict[str, str]) -> str:
    pillar_by_id = {p["id"]: p for p in rules.get("pillars", [])}
    lines = [
        f"# {skill['title']}",
        "## Trigger",
        skill["trigger"],
        "",
        "## Instructions",
    ]
    for pid in skill.get("pillars", []):
        pillar = pillar_by_id.get(pid)
        if not pillar:
            continue
        rule_text = (
            pillar["rule"]
            .strip()
            .replace("$AGENT_PHOENIX_ENDPOINT", ctx["otel_endpoint"])
        )
        lines.append(f"- ({pillar['name']}) {rule_text}")
    lines.append(f"- OTel endpoint: {ctx['otel_endpoint']}/v1/traces")
    lines.append(f"- Owner: {ctx['owner_id']} | Project: {ctx['project_name']}")
    return "\n".join(lines) + "\n"


def _detect_stack(repo_root: Path) -> tuple[str, str]:
    """Mirror hooks/post-checkout's bash stack detection. Returns (stack, default_test_cmd)."""
    if (repo_root / "package.json").exists():
        return "ts-react", "npm test -- --watchAll=false --ci"
    if (
        (repo_root / "requirements.txt").exists()
        or (repo_root / "pyproject.toml").exists()
        or (repo_root / "Pipfile").exists()
    ):
        return "python-fastapi", "pytest"
    if (repo_root / "go.mod").exists():
        return "go", "go test -race ./..."
    return "generic", "echo 'No test command configured'"


def _default_project_name(repo_root: Path) -> str:
    try:
        url = subprocess.run(
            ["git", "remote", "get-url", "origin"],
            cwd=repo_root,
            capture_output=True,
            text=True,
            timeout=5,
        ).stdout.strip()
        if url:
            return url.rsplit("/", 1)[-1].removesuffix(".git")
    except Exception:  # fail-open: no git remote / not a git repo / git not installed all fall back to the dir name below
        pass
    return repo_root.resolve().name


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo-root", default=".")
    ap.add_argument("--rules-file", default=None)
    ap.add_argument("--stack", default=None)
    ap.add_argument("--project-name", default=None)
    ap.add_argument("--owner-id", default=None)
    ap.add_argument("--otel-endpoint", default=None)
    ap.add_argument("--test-cmd", default=None)
    ap.add_argument("--framework-version", default=None)
    ap.add_argument(
        "--check-only",
        action="store_true",
        help="Don't write files — regenerate in memory and diff against what's "
        "already committed. Exits 1 if .cursorrules/CLAUDE.md/skill.md have "
        "drifted from templates/agent-rules.yaml (Pillar 6/7 CI gate).",
    )
    args = ap.parse_args()

    repo_root = Path(args.repo_root)
    detected_stack, detected_test_cmd = _detect_stack(repo_root)

    rules_file = (
        Path(args.rules_file)
        if args.rules_file
        else repo_root / "templates" / "agent-rules.yaml"
    )
    if not rules_file.exists():
        if args.check_only:
            print(f"ℹ️  No rules file at {rules_file} — IDE config drift check skipped.")
            sys.exit(0)
        print(
            f"❌ Rules file not found: {rules_file}. IDE config was NOT regenerated.",
            file=sys.stderr,
        )
        sys.exit(1)

    stack = args.stack or detected_stack
    rules = _load_rules(rules_file)
    ctx = {
        "project_name": args.project_name or _default_project_name(repo_root),
        "owner_id": args.owner_id
        or os.environ.get("AGENT_OWNER_ID", "unknown@unknown"),
        "otel_endpoint": args.otel_endpoint
        or os.environ.get("AGENT_PHOENIX_ENDPOINT", "http://localhost:6006"),
        "test_cmd": args.test_cmd or detected_test_cmd,
        "framework_version": args.framework_version
        or os.environ.get("FRAMEWORK_VERSION", "1.0.0"),
    }

    if args.check_only:
        sys.exit(0 if _check_drift(repo_root, rules, stack, ctx) else 1)

    cursorrules_path = repo_root / ".cursorrules"
    if not cursorrules_path.exists():
        cursorrules_path.write_text(_render_cursorrules(rules, stack, ctx))
        print(
            f"✅ Written .cursorrules ({len(rules.get('pillars', []))} pillars + {stack} addendum) from agent-rules.yaml"
        )

    claude_md_path = repo_root / "CLAUDE.md"
    if not claude_md_path.exists():
        claude_md_path.write_text(_render_claude_md(ctx))
        print("✅ Written CLAUDE.md from agent-rules.yaml")

    for skill in rules.get("skills", []):
        skill_dir = repo_root / ".agents" / "skills" / skill["id"]
        skill_path = skill_dir / "skill.md"
        if not skill_path.exists():
            skill_dir.mkdir(parents=True, exist_ok=True)
            skill_path.write_text(_render_skill(skill, rules, ctx))

    if rules.get("skills"):
        print(
            f"✅ Written Antigravity skill files ({', '.join(s['id'] for s in rules['skills'])}) from agent-rules.yaml"
        )


def _check_drift(repo_root: Path, rules: dict, stack: str, ctx: dict[str, str]) -> bool:
    """Print a diff for any committed IDE config file that no longer matches
    what agent-rules.yaml would generate. Returns True if clean (no drift)."""
    clean = True

    checks = [
        (repo_root / ".cursorrules", _render_cursorrules(rules, stack, ctx)),
        (repo_root / "CLAUDE.md", _render_claude_md(ctx)),
    ]
    for skill in rules.get("skills", []):
        skill_path = repo_root / ".agents" / "skills" / skill["id"] / "skill.md"
        checks.append((skill_path, _render_skill(skill, rules, ctx)))

    for path, expected in checks:
        if not path.exists():
            print(
                f"ℹ️  {path.relative_to(repo_root)} not generated yet — skipping drift check."
            )
            continue
        actual = path.read_text()
        if actual == expected:
            print(f"✅ {path.relative_to(repo_root)} matches agent-rules.yaml")
            continue
        clean = False
        print(f"❌ {path.relative_to(repo_root)} has drifted from agent-rules.yaml:")
        diff = difflib.unified_diff(
            actual.splitlines(keepends=True),
            expected.splitlines(keepends=True),
            fromfile=f"committed/{path.name}",
            tofile=f"generated/{path.name}",
        )
        sys.stdout.writelines(diff)

    return clean


if __name__ == "__main__":
    main()
